"""add restaurant table

Revision ID: 7ab8230e69d5
Revises: 44d3cc608bdd
Create Date: 2026-03-17 18:34:16.040149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab8230e69d5'
down_revision: Union[str, None] = '44d3cc608bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cuisine_type', sa.String(length=100), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('max_capacity > 0', name='check_capacity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.add_column('bookings', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('special_notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bookings', 'longitude')
    op.drop_column('bookings', 'restaurant_address')
    op.drop_column('bookings', 'restaurant_name')
    op.drop_column('bookings', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('restaurant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('restaurant_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'special_notes')
    op.drop_column('bookings', 'restaurant_id')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
