"""add_enum_and_updated_at

Revision ID: 9248d558f273
Revises: fc8ff015b4fa
Create Date: 2026-03-29 19:28:24.657427
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9248d558f273'
down_revision: Union[str, None] = 'fc8ff015b4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 1. Tạo enum type
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status') THEN
                CREATE TYPE booking_status AS ENUM ('pending', 'confirmed', 'cancelled');
            END IF;
        END
        $$;
    """)
    
    # 2. Xóa default value cũ
    op.execute("ALTER TABLE bookings ALTER COLUMN status DROP DEFAULT")
    
    # 3. Đổi kiểu dữ liệu (không có default)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'confirmed', 'cancelled', name='booking_status'),
               nullable=False,
               postgresql_using="status::text::booking_status")
    
    # 4. Thêm default value mới
    op.execute("ALTER TABLE bookings ALTER COLUMN status SET DEFAULT 'pending'")
    
    # Phần còn lại giữ nguyên
    op.drop_constraint('bookings_restaurant_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'restaurants', ['restaurant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('restaurants', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('restaurants', 'updated_at')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_restaurant_id_fkey', 'bookings', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('pending', 'confirmed', 'cancelled', name='booking_status'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    # Xóa enum sau khi downgrade
    op.execute("DROP TYPE IF EXISTS booking_status")
    # ### end Alembic commands ###